services:
  vue:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vue
    deploy:
      replicas: 1
    image: task-manager-vue:latest
    ports:
      - "8080:80"

networks:
  network:
    attachable: true
    driver: overlay
