services:
  vue:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vue
    deploy:
      replicas: 1
    expose:
      - 8080
    environment:
      NODE_ENV: production
    image: task-manager-vue:latest
    networks:
      - network
    ports:
      - "8080:80"

networks:
  network:
    attachable: true
    driver: overlay
