services:
  vue:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: vue
    deploy:
      replicas: 1
    expose:
      - 8080
    image: task-manager-vue:latest
    networks:
      - task-manager
    ports:
      - "8080:80"

networks:
  task-manager:
    attachable: true
    driver: overlay
    external: true
